source 'https://rubygems.org'
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'faraday-retry'
  gem 'fiddle'
  gem 'tzinfo', '>= 1', '< 3'
  gem 'tzinfo-data'
end
gem 'http_parser.rb', '~> 0.6.0', platforms: [:jruby]
gem 'kramdown-parser-gfm'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

gem 'github-pages', '~> 232', group: :jekyll_plugins
gem 'minima', '~> 2.5.1'
group :jekyll_plugins do
  gem 'jekyll-seo-tag', '~> 2.1'
end
gem 'rubocop', group: 'development', require: false
