source "https://rubygems.org"
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
  gem "fiddle"
  gem "faraday-retry"
end
gem "kramdown-parser-gfm"
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

gem "minima", "~> 2.5.1"
gem "github-pages", "~> 232", group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.1"
end
gem 'rubocop', group: 'development', require: false